base_url = "https://xstraven.github.io"
title = "xstraven.github.io"
description = "Personal website of a Berlin-based ML scientist and engineer."
author = "Xstraven"
theme = "terminus"
compile_sass = false
generate_feeds = false
build_search_index = false

taxonomies = [{ name = "tags" }]

[markdown]
render_emoji = true
bottom_footnotes = true
github_alerts = true

[markdown.highlighting]
style = "inline"
theme = "monokai"

[extra]
color_scheme = "terminus"
copy_button = true
favicon_emoji = ">"
layout = "center"
show_default_author = false
main_menu = [
  { name = "blog", url = "blog", trailing_slash = true },
  { name = "github", url = "https://github.com/xstraven", new_tab = true },
]
socials = []
copyright = "© $YEAR $AUTHOR"

[extra.content_security_policy]
enable = true
allowed_domains = []

[extra.responsive_images]
widths = [640, 784, 1280, 1920, 2560]
fallback_width = 1280
